apiVersion: v1
kind: Service
metadata:
  name: whatsapp-backend
spec:
  type: {{ .Values.service.type }}
  selector:
    app: whatsapp-backend
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 3000
