replicaCount: 2

image:
  repository: abhishekyashpal/whatsapp-backend
  tag: stable

environment: staging

resources:
  requests:
    memory: "512Mi"
    cpu: "500m"
  limits:
    memory: "1Gi"
    cpu: "1000m"

ingress:
  enabled: true
  hosts:
    - host: staging.whatsapp-api.yourdomain.com
      paths:
        - path: /
          pathType: Prefix
