replicaCount: 3

image:
  repository: abhishekyashpal/whatsapp-backend
  tag: v1.0.0

environment: prod

resources:
  requests:
    memory: "1Gi"
    cpu: "1000m"
  limits:
    memory: "2Gi"
    cpu: "2000m"

ingress:
  enabled: true
  hosts:
    - host: api.yourdomain.com
      paths:
        - path: /
          pathType: Prefix